apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: {{ .Values.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-master
  type: LoadBalancer  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
