apiVersion: v1
kind: Service
metadata:
  name: jenkins-ubuntu-slave-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: jenkins-slave
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP