- name: Install required packages
  hosts: bastian-host
  become: yes

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present

    - name: Install Google Cloud SDK GKE plugin
      apt:
        name: google-cloud-sdk-gke-gcloud-auth-plugin
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Helm
      shell: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 -o get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh
      args:
        chdir: /tmp

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Configure GKE credentials
      command: gcloud container clusters get-credentials private-cluster --zone us-east1-b --project myproject-387907

    - name: Clone DevOps project repository
      git:
        repo: https://github.com/mohamedsamirspot/Full-Devops-Project_Infrastructure.git
        dest: ~/Full-Devops-Project_Infrastructure

    - name: Run Jenkins playbook
      command: ansible-playbook ~/Full-Devops-Project_Infrastructure/Jenkins-Helm-Yaml-Files-With-Ansible/ansible-helm-jenkins.yaml