- name: Install required packages
  hosts: 35.231.54.103
  become: yes

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present

    - name: Install Google Cloud SDK GKE plugin
      apt:
        name: google-cloud-sdk-gke-gcloud-auth-plugin
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Helm
      shell: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 -o get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh
      args:
        chdir: /tmp

    - name: Install Ansible
      apt:
        name: ansible
        state: present
